# Generated by Django 4.1.4 on 2022-12-26 21:15

import core.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Modificado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('instituicao', models.CharField(max_length=100, verbose_name='Instituição')),
                ('formacao', models.CharField(max_length=200, verbose_name='Formação')),
                ('paragrafo1', models.TextField(max_length=1000, verbose_name='Primeiro Praragrafo')),
                ('paragrafo2', models.TextField(blank=True, max_length=1000, verbose_name='Segundo Praragrafo')),
                ('paragrafo3', models.TextField(blank=True, max_length=1000, verbose_name='Terceiro Praragrafo')),
                ('dataInicio', models.DateField(verbose_name='Data Inicio')),
                ('dataFim', models.DateField(verbose_name='Data Fim')),
            ],
            options={
                'verbose_name': 'Academico',
                'verbose_name_plural': 'Academicos',
            },
        ),
        migrations.CreateModel(
            name='Certificados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Modificado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('curso', models.CharField(max_length=100, verbose_name='Título')),
                ('instituicao', models.CharField(max_length=100, verbose_name='Instituição')),
                ('urlvalidacao', models.URLField(verbose_name='URL Validação')),
                ('totalHoras', models.IntegerField(verbose_name='Total Horas')),
                ('dataConclusao', models.DateField(verbose_name='Data Conclusão')),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_file_path, variations={'thumb': (450, 225)}, verbose_name='Imagem')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
            },
        ),
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Modificado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('comentario', models.TextField(verbose_name='Comentário')),
                ('urlgit', models.URLField(verbose_name='URL GitHub')),
                ('urlsite', models.URLField(verbose_name='URL Site')),
                ('dataConclusao', models.DateField(verbose_name='Data Conclusão')),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_file_path, variations={'thumb': (450, 225)}, verbose_name='Imagem')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug')),
                ('peso', models.IntegerField(verbose_name='Peso do Projeto')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
            },
        ),
        migrations.CreateModel(
            name='VideoApresentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Modificado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('url', models.CharField(max_length=1000, verbose_name='URL')),
                ('data', models.DateField(verbose_name='Data Upload')),
            ],
            options={
                'verbose_name': 'Url',
                'verbose_name_plural': 'Urls',
            },
        ),
    ]
