# Generated by Django 4.1.4 on 2022-12-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='peso',
            field=models.IntegerField(max_length=2, verbose_name='Peso do Projeto'),
        ),
    ]
