# Generated by Django 4.1.4 on 2022-12-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_projetos_peso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Modificado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('instituicao', models.CharField(max_length=100, verbose_name='Instituição')),
                ('formacao', models.CharField(max_length=200, verbose_name='Formação')),
                ('paragrafo1', models.TextField(max_length=1000, verbose_name='Primeiro Praragrafo')),
                ('paragrafo2', models.TextField(max_length=1000, verbose_name='Segundo Praragrafo')),
                ('paragrafo3', models.TextField(max_length=1000, verbose_name='Terceiro Praragrafo')),
                ('dataInicio', models.DateField(verbose_name='Data Inicio')),
                ('dataFim', models.DateField(verbose_name='Data Fim')),
            ],
            options={
                'verbose_name': 'Academico',
                'verbose_name_plural': 'Academicos',
            },
        ),
        migrations.AlterField(
            model_name='projetos',
            name='peso',
            field=models.IntegerField(verbose_name='Peso do Projeto'),
        ),
    ]
