# Generated by Django 4.1.4 on 2023-01-03 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contatoemail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contatoemail',
            options={'verbose_name': 'Contato', 'verbose_name_plural': 'Contatos'},
        ),
    ]
