# Generated by Django 4.1.4 on 2022-12-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_academico_paragrafo3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academico',
            name='paragrafo2',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Segundo Praragrafo'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='paragrafo3',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Terceiro Praragrafo'),
        ),
    ]
