# Generated by Django 4.1.4 on 2022-12-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_certificados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificados',
            name='instituicao',
            field=models.CharField(max_length=100, verbose_name='Instituição'),
        ),
        migrations.AlterField(
            model_name='certificados',
            name='totalHoras',
            field=models.IntegerField(verbose_name='Total Horas'),
        ),
        migrations.AlterField(
            model_name='certificados',
            name='urlvalidacao',
            field=models.URLField(verbose_name='URL Validação'),
        ),
    ]
